### ISSUE TITLE
next steps...

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/PCMDIobs-cmor-tables#12]
@zyuying  Hi YY, I've added input.json and .py files to /test for GPCP 2.3, however have not completed filling them.   I've just noticed that your input data for the reanalysis is pointing to the data you processed with CMOR2 (/clim_obs/obs/atm), ie., not the original raw data (/clim_obs/orig/data)...  don't you think to test and begin using our new system we should be pointing to the raw data?    On Fri I hope to have some time to work on GPCP and a few others.

**Comment by zyuying** [comment]
@gleckler1 I will take a look at GPCP today and we can talk about it sometime tomorrow. Actually, I tried to get CERES variables done last week, but got some error message. It's due to the missing 'positive' argument required by PMPObs_Amon. We don't have it either in the raw data or in the CMOR2 processed data. I'm thinking to add this argument in the code.

**Comment by gleckler1** [comment]
@zyuying  Hello from PLS management meeting!   What variable did CERES fail with?

**Comment by gleckler1** [comment]
@zyuying   I think in your CERES.py you should just be able to add positive = VALUE ("up" or "down").   Did you try that?

**Comment by zyuying** [comment]
@gleckler1  Yes, I tried, but it didn't work.

**Comment by gleckler1** [comment]
@zyuying  OK... why don't you "push" your CERES json and py and I'll give it a try tomorrow.

**Comment by zyuying** [comment]
@gleckler1 Sure. Thank you!

**Comment by durack1** [comment]
@zyuying @gleckler1 I'm back on deck, so happy to help out this week
